### ISSUE TITLE
manage.py update_schema riak error

### ISSUE THREAD

**Issue by hiorws** [zetaops/pyoko#5]
When i tried 
python manage.py update_schema --bucket all
returns error. and traceback;

Traceback (most recent call last):
  File "manage.py", line 12, in <module>
    ManagementCommands(argv[1:])
  File "/app/env/local/lib/python2.7/site-packages/pyoko/manage.py", line 21, in **init**
    getattr(self, self.args.command)()
  File "/app/env/local/lib/python2.7/site-packages/pyoko/manage.py", line 53, in schema_update
    self.robot.run()
  File "/app/env/local/lib/python2.7/site-packages/pyoko/db/schema_update.py", line 42, in run
    bucket_name)))
  File "/app/env/local/lib/python2.7/site-packages/pyoko/db/schema_update.py", line 119, in apply_schema
    self.client.create_search_index(tmp_index_name)
  File "/app/env/src/riak/riak/client/transport.py", line 196, in wrapper
    return self._with_retries(pool, thunk)
  File "/app/env/src/riak/riak/client/transport.py", line 138, in _with_retries
    return fn(transport)
  File "/app/env/src/riak/riak/client/transport.py", line 194, in thunk
    return fn(self, transport, _args, *_kwargs)
  File "/app/env/src/riak/riak/client/operations.py", line 702, in create_search_index
    return transport.create_search_index(index, schema, n_val)
  File "/app/env/src/riak/riak/transports/pbc/transport.py", line 501, in create_search_index
    MSG_CODE_PUT_RESP)
  File "/app/env/src/riak/riak/transports/pbc/connection.py", line 56, in _request
    return self._recv_msg(expect)
  File "/app/env/src/riak/riak/transports/pbc/connection.py", line 174, in _recv_msg
    self._recv_pkt()
  File "/app/env/src/riak/riak/transports/pbc/connection.py", line 199, in _recv_pkt
    % len(nmsglen))
riak.riak_error.RiakError: 'Socket returned short packet length 0 - expected 4'

If i added RIAK_PROTOCOL='http' to environment variables, everything is ok, and scheme updated.

**Comment by evrenesat** [comment]
FIXED
